name: darktable
version: 3.8.1
summary: Virtual lighttable and darkroom for photographers
description: |
  Darktable is an open source photography workflow application and RAW
  developer. A virtual lighttable and darkroom for photographers. It manages
  your digital negatives in a database, lets you view them through a zoomable
  lighttable and enables you to develop raw images and enhance them.

grade: stable
confinement: strict
base: core20
compression: lzo

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  darktable:
    command: usr/bin/darktable --datadir $SNAP/usr/share/darktable --moduledir $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/darktable --configdir $SNAP_USER_DATA --localedir $SNAP/usr/share/locale
    extensions: [gnome-3-38]
    environment:
      GTK_USE_PORTAL: 0
      DISABLE_WAYLAND: 1
    plugs:
      - opengl
      - home
      - removable-media
      - password-manager-service
      - network
      - network-bind
  lesfun-update-data:
    command: usr/bin/lensfun-update-data
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
    plugs:
      - network

slots:
    session-dbus-interface:
        interface: dbus
        name: org.darktable.service
        bus: session

layout:
  /usr/include/clc:
    bind: $SNAP/usr/include/clc
  /usr/lib/clc:
    bind: $SNAP/usr/lib/clc
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gallium-pipe:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gallium-pipe
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/intel-opencl:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/intel-opencl

parts:
    opencl:
        plugin: nil
        stage-packages:
            - mesa-opencl-icd
            - ocl-icd-libopencl1
            - on amd64:
                - intel-opencl-icd
    darktable:
        plugin: cmake
        source: https://github.com/darktable-org/darktable/releases/download/release-$SNAPCRAFT_PROJECT_VERSION/darktable-$SNAPCRAFT_PROJECT_VERSION.tar.xz
        source-checksum: sha256/81ee069054dbde580749b2d3a81cda01b7d169a82ba48731823f3ea560b2bef6
        cmake-parameters:
            - -DCMAKE_BUILD_TYPE=Release
            # Place the data alongside that coming from stage-packages (e.g. the lensfun database)
            - -DCMAKE_INSTALL_PREFIX=/usr
            # Support Lua scripts by way of internal Lua implementation
            - -DDONT_USE_INTERNAL_LUA=Off
            # Don't overly optimize for build CPU-- stay generic
            - -DBINARY_PACKAGE_BUILD=On
            - -DCMAKE_FIND_ROOT_PATH="$SNAPCRAFT_STAGE;/snap/gnome-3-38-2004-sdk/current"
            - -DCMAKE_VERBOSE_MAKEFILE=ON
        stage-packages:
            - libasn1-8-heimdal
            - libcurl3-gnutls
            - libgraphicsmagick-q16-3
            - libgssapi3-heimdal
            - libhcrypto4-heimdal
            - libheimbase1-heimdal
            - libheimntlm0-heimdal
            - libhx509-5-heimdal
            - libimage-exiftool-perl
            - libkrb5-26-heimdal
            - libldap-2.4-2
            - liblensfun-bin
            - liblensfun-data-v1
            - liblensfun1
            - libnghttp2-14
            - libopenexr24
            - libpugixml1v5
            - libroken18-heimdal
            - librtmp1
            - libsasl2-2
            - libssh-4
            - libwind0-heimdal
        build-packages:
            - intltool
            - libgraphicsmagick1-dev
            - liblensfun-dev
            - libopenexr-dev
            - libpugixml-dev
            - libsm-dev
            - libxml2-utils
            - libxrandr-dev
            - pkg-config
            - xsltproc
            # -- Missing jsonschema, problems in noiseprofiles.json might go unnoticed
            # -- GMIC not found

            # Disabled capabilities for now due to interfaces:
            #
            # Camera detection/tethering/importing doesn't work, with no denials.
            # Need to investigate further before enabling this.
            # - libgphoto2-dev
            #
            # Need to test with cups-control interface
            # - libcups2-dev

            # No colord interface
            # - libcolord-dev
            # - libcolord-gtk-dev

        # stage-packages:
            # - libilmbase24
            # - libopenexr24
            # - libpugixml1v5

        build-environment:
            - LDFLAGS: "$LDFLAGS $(pkg-config --libs gtk+-3.0) $(pkg-config --libs sdl2)"
            - CFLAGS: "$CFLAGS $(pkg-config --cflags sdl2)"
            - CXXFLAGS: "$CXXFLAGS $(pkg-config --cflags sdl2)"

        override-build: |
          snapcraftctl build
          PYTHONPATH=$SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages $SNAPCRAFT_PART_INSTALL/usr/bin/lensfun-update-data || echo No updates
          if [ -d /var/lib/lensfun-updates/version_1/]; then
            cp /var/lib/lensfun-updates/version_1/* $SNAPCRAFT_PART_INSTALL/usr/share/lensfun/version_1/
          fi

        after:
            - exiv2
            - osmgpsmap
            - sdl

    exiv2:
        source: https://github.com/Exiv2/exiv2/releases/download/v0.27.5/exiv2-0.27.5-Source.tar.gz
        source-checksum: sha256/35a58618ab236a901ca4928b0ad8b31007ebdc0386d904409d825024e45ea6e2
        plugin: cmake
        cmake-parameters:
            - -DCMAKE_BUILD_TYPE=Release
            - -DCMAKE_INSTALL_PREFIX=/usr
            - -DBUILD_STATIC=OFF
            - -DEXIV2_ENABLE_BMFF=ON
            - -DEXIV2_ENABLE_XMP=ON
            - -DEXIV2_ENABLE_PNG=ON
            - -DEXIV2_ENABLE_NLS=ON
            - -DEXIV2_ENABLE_WEBREADY=ON
        build-packages:
            - libcurl4-gnutls-dev
            - libssl-dev
            - zlib1g-dev

    osmgpsmap:
        source: https://github.com/nzjrs/osm-gps-map/releases/download/1.2.0/osm-gps-map-1.2.0.tar.gz
        source-checksum: sha256/ddec11449f37b5dffb4bca134d024623897c6140af1f9981a8acc512dbf6a7a5
        plugin: autotools
        autotools-configure-parameters:
            - --prefix=/usr
            - --enable-introspection=no
        build-packages:
            - libcurl4-gnutls-dev
            - libssl-dev
            - libsoup2.4-dev

    sdl:
        source: https://libsdl.org/release/SDL2-2.0.16.tar.gz
        source-checksum: sha256/65be9ff6004034b5b2ce9927b5a4db1814930f169c4b2dae0a1e4697075f287b
        plugin: autotools
        autotools-configure-parameters:
            - --prefix=/usr

